---
- hosts: 172.31.37.214
  become: yes
  tasks:
  - name: create file
    file:
      path: /home/ubuntu/testfile
      state: touch
  - include_tasks: myplaybook.yml
  - name: Copy File From Ansible Master to Node
    copy:
      src: mystaticfile
      dest: /home/ubuntu/mystaticfile
      