---
- hosts: 172.31.37.214
  become: yes
  tasks:
  - name: create file
    file:
      path: /home/ubuntu/testfile
      state: touch
  - include_tasks: myplaybook.yml
  - name: Copy File From Ansible Master to Node
    copy:
      src: mystaticfile
      dest: /home/ubuntu/mystaticfile
  - name: copy dynamic file from master to Node
    template:
      src: index.j2
      dest: /var/www/html/index.html
      