---
- hosts: 172.31.37.214
  become: yes
  gather_facts: yes
  tasks:
  - name: Install Web Server
    apt:
      name: apache2
      state: present
    when: ansible_os_family=="Debian"
  - name : Start web Server
    service:
      name: "{{myweb}}"
      state: started
